server:
  port: 8080
  error:
    whitelabel:
      enabled: false

spring:
  # 打开日志颜色输出
  output:
    ansi:
      enabled: detect
  profiles:
    active: dev
  jmx:
    enabled: false


# 日志配置
logging:
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %5level [%15thread] %-50.50(%logger{39}.%method:%-3line) - %msg%n"
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %yellow(%5level) [%15thread] %cyan(%-50.50(%logger{39}.%method:%-3line)) - %msg%n"
  file:
    name: ./logs/javacc-demo/javacc-demo.log
  level:
    com.zhaoyunfei.javacc: debug


# MQTT相关参数
mqtt:
  enable: true
  host: tcp://192.168.3.39:1883
  clientId: ros-patrol-slave
  username: admin
  password: 123456